local AceLocale = LibStub("AceLocale-3.0")
local L = AceLocale:GetLocale( "GearScore" )

GS_Tokens = {
--Teir 9 Tokens


--Teir 8 Tokens
	["45649"] = { ["ItemScore"] = 365, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 1, ["ItemLevel"] = 219 },
	["45647"] = { ["ItemScore"] = 365, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 1, ["ItemLevel"] = 219 },
	["45648"] = { ["ItemScore"] = 365, ["ItemSubType"] = "Protector", ["ItemSlot"] = 1, ["ItemLevel"] = 219 },
    ["45646"] = { ["ItemScore"] = 274, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 10, ["ItemLevel"] = 219 },
	["45644"] = { ["ItemScore"] = 274, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 10, ["ItemLevel"] = 219 },
	["45645"] = { ["ItemScore"] = 274, ["ItemSubType"] = "Protector", ["ItemSlot"] = 10, ["ItemLevel"] = 219 },
	["45637"] = { ["ItemScore"] = 365, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 5, ["ItemLevel"] = 219 },
	["45635"] = { ["ItemScore"] = 365, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 5, ["ItemLevel"] = 219 },
	["45636"] = { ["ItemScore"] = 365, ["ItemSubType"] = "Protector", ["ItemSlot"] = 5, ["ItemLevel"] = 219 },
	["45661"] = { ["ItemScore"] = 274, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 3, ["ItemLevel"] = 219 },
	["45659"] = { ["ItemScore"] = 274, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 3, ["ItemLevel"] = 219 },
	["45660"] = { ["ItemScore"] = 274, ["ItemSubType"] = "Protector", ["ItemSlot"] = 3, ["ItemLevel"] = 219 },
	["45652"] = { ["ItemScore"] = 365, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 7, ["ItemLevel"] = 219 },
	["45650"] = { ["ItemScore"] = 365, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 7, ["ItemLevel"] = 219 },
	["45651"] = { ["ItemScore"] = 365, ["ItemSubType"] = "Protector", ["ItemSlot"] = 7, ["ItemLevel"] = 219 },

--Teir 8.5 Tokens
	["45632"] = { ["ItemScore"] = 385, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 5, ["ItemLevel"] = 226 },
	["45633"] = { ["ItemScore"] = 385, ["ItemSubType"] = "Protector", ["ItemSlot"] = 5, ["ItemLevel"] = 226 },
	["45634"] = { ["ItemScore"] = 385, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 5, ["ItemLevel"] = 226 },
	["45643"] = { ["ItemScore"] = 289, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 10, ["ItemLevel"] = 226 },
	["45641"] = { ["ItemScore"] = 289, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 10, ["ItemLevel"] = 226 },
	["45642"] = { ["ItemScore"] = 289, ["ItemSubType"] = "Protector", ["ItemSlot"] = 10, ["ItemLevel"] = 226 },
	["45640"] = { ["ItemScore"] = 385, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 1, ["ItemLevel"] = 226 },
	["45638"] = { ["ItemScore"] = 385, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 1, ["ItemLevel"] = 226 },
	["45639"] = { ["ItemScore"] = 385, ["ItemSubType"] = "Protector", ["ItemSlot"] = 1, ["ItemLevel"] = 226 },
	["45658"] = { ["ItemScore"] = 289, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 3, ["ItemLevel"] = 226 },
	["45656"] = { ["ItemScore"] = 289, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 3, ["ItemLevel"] = 226 },
	["45657"] = { ["ItemScore"] = 289, ["ItemSubType"] = "Protector", ["ItemSlot"] = 3, ["ItemLevel"] = 226 },
	["45655"] = { ["ItemScore"] = 385, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 7, ["ItemLevel"] = 226 },
	["45653"] = { ["ItemScore"] = 385, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 7, ["ItemLevel"] = 226 },
	["45654"] = { ["ItemScore"] = 385, ["ItemSubType"] = "Protector", ["ItemSlot"] = 7, ["ItemLevel"] = 226 },

--Teir 7 Tokens
	["40618"] = { ["ItemScore"] = 310, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 1, ["ItemLevel"] = 200 },
	["40616"] = { ["ItemScore"] = 310, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 1, ["ItemLevel"] = 200 },
	["40617"] = { ["ItemScore"] = 310, ["ItemSubType"] = "Protector", ["ItemSlot"] = 1, ["ItemLevel"] = 200 },
   	["40615"] = { ["ItemScore"] = 233, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 10, ["ItemLevel"] = 200 },
	["40613"] = { ["ItemScore"] = 233, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 10, ["ItemLevel"] = 200 },
	["40614"] = { ["ItemScore"] = 233, ["ItemSubType"] = "Protector", ["ItemSlot"] = 10, ["ItemLevel"] = 200 },
	["40612"] = { ["ItemScore"] = 310 , ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 5, ["ItemLevel"] = 200 },
	["40610"] = { ["ItemScore"] = 310 , ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 5, ["ItemLevel"] = 200 },
	["40611"] = { ["ItemScore"] = 310, ["ItemSubType"] = "Protector", ["ItemSlot"] = 5, ["ItemLevel"] = 200 },
	["40624"] = { ["ItemScore"] = 233, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 3, ["ItemLevel"] = 200 },
	["40622"] = { ["ItemScore"] = 233, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 3, ["ItemLevel"] = 200 },
	["40623"] = { ["ItemScore"] = 233, ["ItemSubType"] = "Protector", ["ItemSlot"] = 3, ["ItemLevel"] = 200 },
	["40621"] = { ["ItemScore"] = 310, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 7, ["ItemLevel"] = 200 },
	["40619"] = { ["ItemScore"] = 310, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 7, ["ItemLevel"] = 200 },
	["40620"] = { ["ItemScore"] = 310, ["ItemSubType"] = "Protector", ["ItemSlot"] = 7, ["ItemLevel"] = 200 },

--Teir 7.5 Tokens
	["40633"] = { ["ItemScore"] = 348, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 1, ["ItemLevel"] = 213 },
	["40631"] = { ["ItemScore"] = 348, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 1, ["ItemLevel"] = 213 },
	["40632"] = { ["ItemScore"] = 348, ["ItemSubType"] = "Protector", ["ItemSlot"] = 1, ["ItemLevel"] = 213 },
	["40630"] = { ["ItemScore"] = 261, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 10, ["ItemLevel"] = 213 },
	["40628"] = { ["ItemScore"] = 261, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 10, ["ItemLevel"] = 213 },
	["40629"] = { ["ItemScore"] = 261, ["ItemSubType"] = "Protector", ["ItemSlot"] = 10, ["ItemLevel"] = 213 },
	["40627"] = { ["ItemScore"] = 348, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 5, ["ItemLevel"] = 213 },
	["40625"] = { ["ItemScore"] = 348, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 5, ["ItemLevel"] = 213 },
	["40626"] = { ["ItemScore"] = 348, ["ItemSubType"] = "Protector", ["ItemSlot"] = 5, ["ItemLevel"] = 213 },
	["40639"] = { ["ItemScore"] = 261, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 3, ["ItemLevel"] = 213 },
	["40637"] = { ["ItemScore"] = 261, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 3, ["ItemLevel"] = 213 },
	["40638"] = { ["ItemScore"] = 261, ["ItemSubType"] = "Protector", ["ItemSlot"] = 3, ["ItemLevel"] = 213 },
	["40636"] = { ["ItemScore"] = 348, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 7, ["ItemLevel"] = 213 },
	["40634"] = { ["ItemScore"] = 348, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 7, ["ItemLevel"] = 213 },
	["40635"] = { ["ItemScore"] = 348, ["ItemSubType"] = "Protector", ["ItemSlot"] = 7, ["ItemLevel"] = 213 },

}

GS_Factions = {
	["H"] = "Horde",
	["A"] = "Alliance",
	["Horde"] = "H",
	["Alliance"] = "A"
}

GS_Races = { 
	["HU"] = L["Human"],
	["DW"] = L["Dwarf"],
	["GN"] = L["Gnome"],
	["DR"] = L["Draenei"],
	["NE"] = L["NightElf"],
	["OR"] = L["Orc"],
	["TA"] = L["Tauren"],
	["TR"] = L["Troll"],
	["BE"] = L["BloodElf"],
	["UN"] = L["Undead"],
	["Human"] = "HU",
	["Dwarf"] = "DW",
	["Gnome"] = "GN",
	["Draenei"] = "DR",
	["NightElf"] = "NE",
	["Orc"] = "OR",
	["Tauren"] = "TA",
	["Troll"] = "TR",
	["BloodElf"] = "BE",
	["Scourge"] = "UN",
}

GS_Sexes = { [1] = "Neutral", [2] = "Male", [3] = "Female" }

GS_Classes = {
	["WA"] = L["Warrior"],
	["DK"] = L["Death Knight"],
	["PA"] = L["Paladin"],
	["SH"] = L["Shaman"],
	["HU"] = L["Hunter"],
	["DR"] = L["Druid"],
	["RO"] = L["Rogue"],
	["WK"] = L["Warlock"],
	["PR"] = L["Priest"],
	["MA"] = L["Mage"],
	["WARRIOR"] = "WA",
	["DEATHKNIGHT"] = "DK",
	["PALADIN"] = "PA",
	["SHAMAN"] = "SH",
	["HUNTER"] = "HU",
	["DRUID"] = "DR",
	["ROGUE"] = "RO",
	["WARLOCK"] = "WK",
	["PRIEST"] = "PR",
	["MAGE"] = "MA",
}

GS_EnglishClasses = {
	["WA"] = "WARRIOR",
	["DK"] = "DEATHKNIGHT",
	["PA"] = "PALADIN",
	["SH"] = "SHAMAN",
	["HU"] = "HUNTER",
	["DR"] = "DRUID",
	["RO"] = "ROGUE",
	["WK"] = "WARLOCK",
	["PR"] = "PRIEST",
	["MA"] = "MAGE",
}

GS_Texture = {
	[1] = GS_Slot1,
	[2] = GS_Slot2,
	[3] = GS_Slot3,
	[4] = GS_Slot4,
	[5] = GS_Slot5,
	[6] = GS_Slot6,
	[7] = GS_Slot7,
	[8] = GS_Slot8,
	[9] = GS_Slot9,
	[10] = GS_Slot10,
	[11] = GS_Slot11,
	[12] = GS_Slot12,
	[13] = GS_Slot13,
	[14] = GS_Slot14,
	[15] = GS_Slot15,
	[16] = GS_Slot16,
	[17] = GS_Slot17,
	[18] = GS_Slot18,
}


GS_ClassInfo = {
	["Warrior"]  = {
		["Name"] = "Warrior",
		["Key"] = "WA",
		["Red"] = 0.78,
		["Green"] = 0.61,
		["Blue"] = 0.43,
		["Equip"] = {
			["Plate"] = 1,
			["Shields"] = 1,
			["Bows"] = 1,
			["Crossbows"] = 1,
			["Guns"] = 1,
			["Thrown"] = 1,
			["Daggers"] = 1,
			["Fist Weapons"] = 1,
			["Miscellaneous"] = 1,
			["One-Handed Maces"] = 1,
			["One-Handed Swords"] = 1,
			["Polearms"] = 1,
			["Staves"] = 1,
			["Two-Handed Axes"] = 1,
			["Two-Handed Maces"] = 1,
			["Two-Handed Swords"] = 1,
			["Protector"] = 1,
		}
	},
	["Death Knight"] = {
		["Name"] = "Death Knight",
		["Key"] = "WA",
		["Red"] = 0.77,
		["Green"] = 0.12,
		["Blue"] = 0.23,
		["Equip"] = {
			["Plate"] = 1,
			["Sigils"] = 1,
			["Miscellaneous"] = 1,
			["One-Handed Axes"] = 1,
			["One-Handed Maces"] = 1,
			["One-Handed Swords"] = 1,
			["Polearms"] = 1,
			["Two-Handed Axes"] = 1,
			["Two-Handed Maces"] = 1,
			["Two-Handed Swords"] = 1,
			["Vanquisher"] = 1,
		}
	},
	["Paladin"] = {
		["Name"] = "Paladin",
		["Key"] = "PA",
		["Red"] = 0.96,
		["Green"] = 0.55,
		["Blue"] = 0.73,
		["Equip"] = {
			["Plate"] = 1,
			["Librams"] = 1,
			["Shields"] = 1,
			["Miscellaneous"] = 1,
			["One-Handed Axes"] = 1,
			["One-Handed Maces"] = 1,
			["One-Handed Swords"] = 1,
			["Polearms"] = 1,
			["Two-Handed Axes"] = 1,
			["Two-Handed Maces"] = 1,
			["Two-Handed Swords"] = 1,
			["Conqueror"] = 1,
		}
	},
	["Druid"] = {
		["Name"] = "Druid",
		["Key"] = "DR",
		["Red"] = 1.00,
		["Green"] = 0.49,
		["Blue"] = 0.04,
		["Equip"] = {
			["Leather"] = 1,
			["Idols"] = 1,
			["Miscellaneous"] = 1,
			["One-Handed Maces"] = 1,
			["Daggers"] = 1,
			["Polearms"] = 1,
			["Staves"] = 1,
			["Two-Handed Maces"] = 1,
            ["Vanquisher"] = 1,
		}
	},
	["Hunter"] = {
		["Name"] = "Hunter",
		["Key"] = "HU",
		["Red"] = 0.67,
		["Green"] = 0.83,
		["Blue"] = 0.45,
		["Equip"] = {
			["Mail"] = 1,
			["Bows"] = 1,
			["Crossbows"] = 1,
			["Guns"] = 1,
			["Thrown"] = 1,
			["Daggers"] = 1,
			["Fist Weapons"] = 1,
			["Miscellaneous"] = 1,
			["One-Handed Axes"] = 1,
			["One-Handed Swords"] = 1,
			["Polearms"] = 1,
			["Staves"] = 1,
			["Two-Handed Axes"] = 1,
			["Two-Handed Swords"] = 1,
            ["Protector"] = 1,
		}
	},
	["Mage"] = {
		["Name"] = "Mage",
		["Key"] = "MA",
		["Red"] = 0.41,
		["Green"] = 0.80,
		["Blue"] = 0.94,
		["Equip"] = {
			["Cloth"] = 1,
			["Wands"] = 1,
			["Daggers"] = 1,
			["Miscellaneous"] = 1,
			["One-Handed Swords"] = 1,
			["Staves"] = 1,
            ["Vanquisher"] = 1,
		}
	},
	["Priest"] = {
		["Name"] = "Priest",
		["Key"] = "PR",
		["Red"] = 1.00,
		["Green"] = 1.00,
		["Blue"] = 1.00,
		["Equip"] = {
			["Cloth"] = 1,
			["Wands"] = 1,
			["Daggers"] = 1,
			["Miscellaneous"] = 1,
			["One-Handed Maces"] = 1,
			["Staves"] = 1,
            ["Conqueror"] = 1,
		}
	},
	["Rogue"] = {
		["Name"] = "Rogue",
		["Key"] = "RO",
		["Red"] = 1.00,
		["Green"] = 0.96,
		["Blue"] = 0.41,
		["Equip"] = {
			["Leather"] = 1,
			["Bows"] = 1,
			["Crossbows"] = 1,
			["Guns"] = 1,
			["Thrown"] = 1,
			["Daggers"] = 1,
			["Fist Weapons"] = 1,
			["Miscellaneous"] = 1,
			["One-Handed Maces"] = 1,
			["One-Handed Swords"] = 1,
            ["Vanquisher"] = 1,
		 }
	},
	["Shaman"] = {
		["Name"] = "Shaman",
		["Key"] = "SH",
		["Red"] = 0.14,
		["Green"] = 0.35,
		["Blue"] = 1.00,
		["Equip"] = {
			["Mail"] = 1,
			["Totems"] = 1,
			["Shields"] = 1,
			["Fist Weapons"] = 1,
			["One-Handed Axes"] = 1,
			["Daggers"] = 1,
			["Miscellaneous"] = 1,
			["One-Handed Axes"] = 1,
			["One-Handed Maces"] = 1,
			["Staves"] = 1,
			["Two-Handed Axes"] = 1,
			["Two-Handed Maces"] = 1,
            ["Protector"] = 1,
		}
	},
	["Warlock"] = {
		["Name"] = "Warlock",
		["Key"] = "WK",
		["Red"] = 0.58,
		["Green"] = 0.51,
		["Blue"] = 0.79,
		["Equip"] = {
			["Cloth"] = 1,
			["Wands"] = 1,
			["Daggers"] = 1,
			["Miscellaneous"] = 1,
			["One-Handed Swords"] = 1,
			["Staves"] = 1,
            ["Conqueror"] = 1,
		}
	}
}

GS_ItemTypes = {
	["INVTYPE_RELIC"] = { ["SlotMOD"] = 0.3164, ["ItemSlot"] = 18, ["Enchantable"] = false},
	["INVTYPE_TRINKET"] = { ["SlotMOD"] = 0.5625, ["ItemSlot"] = 33, ["Enchantable"] = false },
	["INVTYPE_2HWEAPON"] = { ["SlotMOD"] = 2.000, ["ItemSlot"] = 16, ["Enchantable"] = true },
	["INVTYPE_WEAPONMAINHAND"] = { ["SlotMOD"] = 1.0000, ["ItemSlot"] = 16, ["Enchantable"] = true },
	["INVTYPE_WEAPONOFFHAND"] = { ["SlotMOD"] = 1.0000, ["ItemSlot"] = 17, ["Enchantable"] = true },
	["INVTYPE_RANGED"] = { ["SlotMOD"] = 0.3164, ["ItemSlot"] = 18, ["Enchantable"] = true },
	["INVTYPE_THROWN"] = { ["SlotMOD"] = 0.3164, ["ItemSlot"] = 18, ["Enchantable"] = false },
	["INVTYPE_RANGEDRIGHT"] = { ["SlotMOD"] = 0.3164, ["ItemSlot"] = 18, ["Enchantable"] = false },
	["INVTYPE_SHIELD"] = { ["SlotMOD"] = 1.0000, ["ItemSlot"] = 17, ["Enchantable"] = true },
	["INVTYPE_WEAPON"] = { ["SlotMOD"] = 1.0000, ["ItemSlot"] = 36, ["Enchantable"] = true },
	["INVTYPE_HOLDABLE"] = { ["SlotMOD"] = 1.0000, ["ItemSlot"] = 17, ["Enchantable"] = false },
	["INVTYPE_HEAD"] = { ["SlotMOD"] = 1.0000, ["ItemSlot"] = 1, ["Enchantable"] = true },
	["INVTYPE_NECK"] = { ["SlotMOD"] = 0.5625, ["ItemSlot"] = 2, ["Enchantable"] = false },
	["INVTYPE_SHOULDER"] = { ["SlotMOD"] = 0.7500, ["ItemSlot"] = 3, ["Enchantable"] = true },
	["INVTYPE_CHEST"] = { ["SlotMOD"] = 1.0000, ["ItemSlot"] = 5, ["Enchantable"] = true },
	["INVTYPE_ROBE"] = { ["SlotMOD"] = 1.0000, ["ItemSlot"] = 5, ["Enchantable"] = true },
	["INVTYPE_WAIST"] = { ["SlotMOD"] = 0.7500, ["ItemSlot"] = 6, ["Enchantable"] = false },
	["INVTYPE_LEGS"] = { ["SlotMOD"] = 1.0000, ["ItemSlot"] = 7, ["Enchantable"] = true },
	["INVTYPE_FEET"] = { ["SlotMOD"] = 0.75, ["ItemSlot"] = 8, ["Enchantable"] = true },
	["INVTYPE_WRIST"] = { ["SlotMOD"] = 0.5625, ["ItemSlot"] = 9, ["Enchantable"] = true },
	["INVTYPE_HAND"] = { ["SlotMOD"] = 0.7500, ["ItemSlot"] = 10, ["Enchantable"] = true },
	["INVTYPE_FINGER"] = { ["SlotMOD"] = 0.5625, ["ItemSlot"] = 31, ["Enchantable"] = false },
	["INVTYPE_CLOAK"] = { ["SlotMOD"] = 0.5625, ["ItemSlot"] = 15, ["Enchantable"] = true },
}

GS_DefaultSettings = {
	["KeepFaction"] = -1,
	["Player"] = 1,
	["Item"] = 1,
	["Show"] = 1,
	["Special"] = 1,
	["PVE"] = -1,
	["PVP"] = -1,
	["Communication"] = 1,
	["Compare"] = -1,
	["CHAT"] = -1,
	["Level"] = -1,
	["Average"] = -1,
	["Date2"] = 1,
	["ML"] = -1,
	["Slider"] = 10,
	["AutoPrune"] = 1,
	["ShowHelp"] = 1,
	["MinLevel"] = 80,
	["Detail"] = -1,
	["Restrict"] = 2, 
	["HNaxx"] = 3500,
	["Ulduar"] = 3850,
	["HUlduar"] = 4000,
	["Naxx"] = 3000,
	["HMaly"] = 3800,
	["Heroics"] = 2600,
	["Archavon"] = 2900,
	["Sarth"] = 2950,
	["HArchavon"] = 3350,
	["Malygos"] = 3400,
	["HSarth"] = 3450,
	["Emalon"] = 3650,
	["HEmalon"] = 3750,
	["HCrusade"] = 4500,
	["Crusade"] = 4100,
	["DatabaseAgeSlider"] = 30,
	["ShowSpecScores"] = {},
}

GS_TextureFiles = {
	[1] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Head.blp",
	[2] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Neck.blp",
	[3] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Shoulder.blp",
	[4] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Chest.blp",
	[5] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Chest.blp",
	[6] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Waist.blp",
	[7] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Legs.blp",
	[8] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Feet.blp",
	[9] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Wrists.blp",
	[10] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Hands.blp",
	[11] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-RFinger.blp",
	[12] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Finger.blp",
	[13] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Trinket.blp",
	[14] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Trinket.blp",
	[15] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Chest.blp",
	[16] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-MainHand.blp",
	[17] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-SecondaryHand.blp",
	[18] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Ranged.blp",
}

GS_Special = {
	["A"] = "Author of GearScore",
	["B"] = "Official Sponsor of GearScore",
	["C"] = "Official GearScore Guild",
	["D"] = "Official Nemesis of GearScore",
	["E"] = "Killing Machine",
	["F"] = "Petscore: 9001",
 	["Pauladin"] = { ["Realm"] = "Elune", ["Type"] = "B" },
 	
 	["Wolfric"] = { ["Realm"] = "Khaz'Goroth", ["Type"] = "B" },
 	["Coastar"] = { ["Realm"] = "Khaz'Goroth", ["Type"] = "B" },
 	["Alekzander"] = { ["Realm"] = "Agamaggan", ["Type"] = "B" },
 	["Decks"] = { ["Realm"] = "Detheroc", ["Type"] = "B" },
 	["Dram"] = { ["Realm"] = "Duskwood", ["Type"] = "B" },
 	["Moophasa"] = { ["Realm"] = "Silver Hand", ["Type"] = "B" },
 	["Spirts"] = { ["Realm"] = "Khaz'Goroth", ["Type"] = "B" },
 	--["Wizzardly"] = { ["Realm"] = "Khaz'Goroth", ["Type"] = "B" },
 	--["Cloroangel"] = { ["Realm"] = "Khaz'Goroth", ["Type"] = "B" },
 	["Aeonel"] = { ["Realm"] = "Proudmoore", ["Type"] = "B" },
	["Lollygimon"] = { ["Realm"] = "Caelestrasz", ["Type"] = "B" },  		
	["Midshipman"] = { ["Realm"] = "Fenris", ["Type"] = "B" },  		
	["Saruk"] = { ["Realm"] = "Mal'Ganis", ["Type"] = "B" },  		
	["Volstormbrew"] = { ["Realm"] = "Detheroc", ["Type"] = "B" },  		
	["Shinnobe"] = { ["Realm"] = "Stormreaver", ["Type"] = "B" },  		
	["Spontaneous"] = { ["Realm"] = "Stormreaver", ["Type"] = "B" },  		
	["Nias"] = { ["Realm"] = "Stormreaver", ["Type"] = "B" },  		
	["Yaks"] = { ["Realm"] = "Balnazzar", ["Type"] = "B" },  		
	["Andresh"] = { ["Realm"] = "Uldaman", ["Type"] = "B" },  		
	["Atelyn"] = { ["Realm"] = "Thunderhorn", ["Type"] = "B" },  
	["UltraJames"] = { ["Realm"] = "Stormscale", ["Type"] = "B" }, 		
	--["Jubali"] = { ["Realm"] = "Frostmourne", ["Type"] = "B" }, 
	["Dalha"] = { ["Realm"] = "Dragonblight", ["Type"] = "B" }, 
	["Delitahyral"] = { ["Realm"] = "Shandris", ["Type"] = "B" }, 
	["Deathhaeven"] = { ["Realm"] = "Eldre'thalas", ["Type"] = "B" }, 
	["Nareli"] = { ["Realm"] = "Detheroc", ["Type"] = "D" }, 
	["Dalha"] = { ["Realm"] = "Dragonblight", ["Type"] = "B" }, 
	["Neisha"] = { ["Realm"] = "Stormreaver", ["Type"] = "B" }, 
	["Tentontotem"] = { ["Realm"] = "Destromath", ["Type"] = "B" }, 
	["GryphonMD"] = { ["Realm"] = "Kargath", ["Type"] = "B" }, 
	["Judeondethus"] = { ["Realm"] = "Detheroc", ["Type"] = "B" }, 	
	["Greatmelinko"] = { ["Realm"] = "Detheroc", ["Type"] = "B" }, 
	["Eshia"] = { ["Realm"] = "Stormreaver", ["Type"] = "B" }, 
 	["Greatmelinko"] = { ["Realm"] = "Detheroc", ["Type"] = "B" }, 
 	["Hiivolt"] = { ["Realm"] = "Detheroc", ["Type"] = "B" }, 
 	["Tlor"] = { ["Realm"] = "Kirin Tor", ["Type"] = "B" }, 
 	["Arachna"] = { ["Realm"] = "Kel'Thuzad", ["Type"] = "B" },
 	["Belarr"] = { ["Realm"] = "Misha", ["Type"] = "B" }, 
 	["Zarniwhoop"] = { ["Realm"] = "Ysera", ["Type"] = "B" },  
 	["Faculty"] = { ["Realm"] = "Feathermoon", ["Type"] = "B" },  
 	["Round"] = { ["Realm"] = "Thunderhorn", ["Type"] = "B" }, 
 	["Berlioz"] = { ["Realm"] = "Thunderhorn", ["Type"] = "B" }, 
 	["Huzzan"] = { ["Realm"] = "Detheroc", ["Type"] = "B" }, 
 	["Lawlcat"] = { ["Realm"] = "Detheroc", ["Type"] = "B" },  	
 	["Khyu"] = { ["Realm"] = "Aggramar", ["Type"] = "B" },  	
 	["Tricksybell"] = { ["Realm"] = "Dentarg", ["Type"] = "B" },  	
 	["Quixotek"] = { ["Realm"] = "Kel'Thuzad", ["Type"] = "B" },  	
 	["Chetnik"] = { ["Realm"] = "Gurubashi", ["Type"] = "B" },  	
 	["Tekfour"] = { ["Realm"] = "Dreadmaul", ["Type"] = "B" }, 
 	["Tekfrost"] = { ["Realm"] = "Dreadmaul", ["Type"] = "B" }, 
 	["Adi"] = { ["Realm"] = "Elune", ["Type"] = "B" }, 
 	["Adibou"] = { ["Realm"] = "Elune", ["Type"] = "B" },  	 	
 	["Zinya"] = { ["Realm"] = "Azjol-Nerub", ["Type"] = "B" }, 
 	["Temmi"] = { ["Realm"] = "Dath'Remar", ["Type"] = "B" }, 
	["Tejal"] = { ["Realm"] = "Cairne", ["Type"] = "B" }, 
	["Doriecycline"] = { ["Realm"] = "Dreadmaul", ["Type"] = "B" }, 
	["Cayman"] = { ["Realm"] = "Shandris", ["Type"] = "B" }, 
 	["Verîx"] = { ["Realm"] = "Stormreaver", ["Type"] = "B" },
 	["Asulla"] = { ["Realm"] = "Stormreaver", ["Type"] = "B" },
	["Halcyana"] = { ["Realm"] = "Detheroc", ["Type"] = "B" },
	["Midiga"] = { ["Realm"] = "Stormreaver", ["Type"] = "B" },	
	 	
----------------------------
	["Midiga"] = { ["Realm"] = "IceCrown", ["Type"] = "B" },		 	
	["Drgoodhead "] = { ["Realm"] = "Stormreaver", ["Type"] = "B" },		 	
	["Squirrelly"] = { ["Realm"] = "Elune", ["Type"] = "B" },		 	
	["Atewheaties"] = { ["Realm"] = "Elune", ["Type"] = "B" },		 	
	["Shz"] = { ["Realm"] = "Gorefiend", ["Type"] = "B" },		 	
	["Zevilone"] = { ["Realm"] = "Llane", ["Type"] = "B" },		 	
	["Thorkeld"] = { ["Realm"] = "Shadow Council", ["Type"] = "B" },		 	
	["Vaxum"] = { ["Realm"] = "Spirestone", ["Type"] = "B" },		 	
	["Muru"] = { ["Realm"] = "Spirestone", ["Type"] = "B" },		 	
	["Moodle"] = { ["Realm"] = "Spirestone", ["Type"] = "B" },		 	
	["Anzio"] = { ["Realm"] = "Bladefist", ["Type"] = "B" },		 	
	["Ggoddess"] = { ["Realm"] = "Madoran", ["Type"] = "B" },		 	
	["Rakkan"] = { ["Realm"] = "Lothar", ["Type"] = "B" },		 	
	["Taliaran"] = { ["Realm"] = "Grim Batol", ["Type"] = "B" },		 	
	["Dartagg"] = { ["Realm"] = "Crushridge", ["Type"] = "B" },		 	
	["Sethr"] = { ["Realm"] = "Crushridge", ["Type"] = "B" },		 	
	["Diosan"] = { ["Realm"] = "Scarlet Crusade", ["Type"] = "B" },		 	
	["Renth"] = { ["Realm"] = "Dragonblight", ["Type"] = "B" },		 	
	["Wherezwaldo"] = { ["Realm"] = "Magtheridon", ["Type"] = "B" },		 	
	["Mif"] = { ["Realm"] = "Proudmoore", ["Type"] = "B" },		 	
	["Lotorin"] = { ["Realm"] = "Thunderhorn", ["Type"] = "B" },		 	
	["Starrìe"] = { ["Realm"] = "Malfurion", ["Type"] = "B" },		 	
	["Jthome"] = { ["Realm"] = "Lightning's Blade", ["Type"] = "B" },		 	
	["Retmeat"] = { ["Realm"] = "Cairne", ["Type"] = "B" },		 	
	["Catzilla"] = { ["Realm"] = "Draenor", ["Type"] = "B" },		 	
	["Lonnie"] = { ["Realm"] = "Draenor", ["Type"] = "B" },		 	
	["Millantis"] = { ["Realm"] = "Archimonde", ["Type"] = "B" },		 	
	["Benzy"] = { ["Realm"] = "Alterac Mountains", ["Type"] = "B" },		 	
	["Deaddolly"] = { ["Realm"] = "Windrunner", ["Type"] = "B" },		 	
	["Erd"] = { ["Realm"] = "Burning Legion", ["Type"] = "B" },		 	
	["Enigmà"] = { ["Realm"] = "Darksorrow", ["Type"] = "B" },		 	
	["Deaddolly"] = { ["Realm"] = "Windrunner", ["Type"] = "B" },		 	
	["Dragonas"] = { ["Realm"] = "Lethon", ["Type"] = "B" },		 	
	["Salamando"] = { ["Realm"] = "Khadgar", ["Type"] = "B" },		 	
	["Alzinator"] = { ["Realm"] = "Shadowsong", ["Type"] = "B" },		 	
	["Junebee"] = { ["Realm"] = "Turalyon", ["Type"] = "B" },		 		
------------------------------	 	
-- 6/3/2010
	["Neysaa"] = { ["Realm"] = "Skywall", ["Type"] = "B" },			 	
	["Halcyana"] = { ["Realm"] = "Detheroc", ["Type"] = "E" },
	["Kobekuro"] = { ["Realm"] = "Detheroc", ["Type"] = "E" },
	["Kobeyama"] = { ["Realm"] = "Detheroc", ["Type"] = "E" },
	["Sophiayuki"] = { ["Realm"] = "Detheroc", ["Type"] = "E" },
	["Praetori"] = { ["Realm"] = "Draenor", ["Type"] = "B" },
	["Strahdvonzar"] = { ["Realm"] = "Quel'Thalas", ["Type"] = "B" },
	["Rhakark"] = { ["Realm"] = "Kirin Tor", ["Type"] = "B" },
	["Jazzia"] = { ["Realm"] = "Earthen Ring", ["Type"] = "B" },
	["Diilemmaz"] = { ["Realm"] = "Proudmoore", ["Type"] = "B" },
	["Evilenigma"] = { ["Realm"] = "Darksorrow", ["Type"] = "B" },
	["Bittles"] = { ["Realm"] = "Detheroc", ["Type"] = "B" },
	["Soilwork"] = { ["Realm"] = "Kirin Tor", ["Type"] = "B" },
	["Flayrot"] = { ["Realm"] = "Lothar", ["Type"] = "B" },
	["Direbear"] = { ["Realm"] = "Quel'Thalas", ["Type"] = "F" },
	["Vampiroth"] = { ["Realm"] = "Zul'jin", ["Type"] = "B" },
	["Tumtumm"] = { ["Realm"] = "Proudmoore", ["Type"] = "B" },
	["Winsticles"] = { ["Realm"] = "Frostmourne", ["Type"] = "B" },
	["Rekviem"] = { ["Realm"] = "Elune", ["Type"] = "B" },
	["Rîddîck"] = { ["Realm"] = "Madoran", ["Type"] = "B" },
	["Drakekitty"] = { ["Realm"] = "Proudmoore", ["Type"] = "B" },
	["Paladio"] = { ["Realm"] = "Area 52", ["Type"] = "B" },
	["Modellista"] = { ["Realm"] = "Khaz'Goroth", ["Type"] = "B" },
	["Cablitin"] = { ["Realm"] = "Proudmoore", ["Type"] = "B" },
	["Sneakycab"] = { ["Realm"] = "Proudmoore", ["Type"] = "B" },
	["Uselessllama"] = { ["Realm"] = "Spirestone", ["Type"] = "B" },
	["Penetråtion"] = { ["Realm"] = "Caelestrasz", ["Type"] = "B" },	 	
	
	["Funstar"] = { ["Realm"] = "Mal'Ganis", ["Type"] = "B" },
	["Omnimen"] = { ["Realm"] = "Agamaggen", ["Type"] = "B" },
	["Dotimusprime"] = { ["Realm"] = "Black DragonFlight", ["Type"] = "B" },
	["Sajuukkhar"] = { ["Realm"] = "Nordrassil", ["Type"] = "B" },
	["Noggienog"] = { ["Realm"] = "Windrunner", ["Type"] = "B" },
	["Stevelrwin"] = { ["Realm"] = "Aggramar", ["Type"] = "B" },
	["Facerollftw"] = { ["Realm"] = "Aggramar", ["Type"] = "B" },
	["Healsforhugs"] = { ["Realm"] = "Aggramar", ["Type"] = "B" },
	["Droodzz"] = { ["Realm"] = "Bruning Legion", ["Type"] = "B" },
	
	 	
------------------------------	 	 	
	["Arxkanite"] = { ["Realm"] = "Detheroc", ["Type"] = "A" },
	["Josephsmith"] = { ["Realm"] = "Detheroc", ["Type"] = "B" },
	["Choku"] = { ["Realm"] = "Magtheridon", ["Type"] = "B" },
	["Murmilude"] = { ["Realm"] = "Blade's Edge", ["Type"] = "B" },
	["Rangitor"] = { ["Realm"] = "Khaz'Goroth", ["Type"] = "B" },
	["Keightie"] = { ["Realm"] = "Detheroc", ["Type"] = "B" },
    	--["Kymax"] = { ["Realm"] = "Detheroc", ["Type"] = "A" },
    	["Zanier"] = { ["Realm"] = "Cairne", ["Type"] = "B" },    
    	--["Cuppycakes"] = { ["Realm"] = "Detheroc", ["Type"] = "A" },
    	--["Sausagefest"] = { ["Realm"] = "Detheroc", ["Type"] = "B" },
    	["Rogue Angels"] = { ["Realm"] = "Detheroc", ["Type"] = "C" },
}

GS_Rarity = {
	[0] = { Red = 0.55,	Green = 0.55, Blue = 0.55 },
	[1] = {	Red = 1.00,	Green = 1.00, Blue = 1.00 },
	[2] = {	Red = 0.12,	Green = 1.00, Blue = 0.00 },
	[3] = {	Red = 0.00,	Green = 0.50, Blue = 1.00 },
	[4] = {	Red = 0.69, Green = 0.28, Blue = 0.97 },
	[5] = { Red = 0.94,	Green = 0.09, Blue = 0.00 },
	[6] = {	Red = 1.00,	Green = 0.00, Blue = 0.00 },
	[7] = {	Red = 0.90,	Green = 0.80, Blue = 0.50 },
}

GS_Formula = {
	["A"] = {
		[4] = { ["A"] = 91.4500, ["B"] = 0.6500 },
		[3] = { ["A"] = 81.3750, ["B"] = 0.8125 },
		[2] = { ["A"] = 73.0000, ["B"] = 1.0000 }
	},
	["B"] = {
		[4] = { ["A"] = 26.0000, ["B"] = 1.2000 },
		[3] = { ["A"] = 0.7500, ["B"] = 1.8000 },
		[2] = { ["A"] = 8.0000, ["B"] = 2.0000 },
		[1] = { ["A"] = 0.0000, ["B"] = 2.2500 }
	}
}

GS_Quality = {
	[6000] = {
		["Red"] = { ["A"] = 0.94, ["B"] = 5000, ["C"] = 0.00006, ["D"] = 1 },
		["Green"] = { ["A"] = 0.47, ["B"] = 5000, ["C"] = 0.00047, ["D"] = -1 },
		["Blue"] = { ["A"] = 0, ["B"] = 0, ["C"] = 0, ["D"] = 0 },
		["Description"] = "Legendary"
	},
	[5000] = {
		["Red"] = { ["A"] = 0.69, ["B"] = 4000, ["C"] = 0.00025, ["D"] = 1 },
		["Green"] = { ["A"] = 0.28, ["B"] = 4000, ["C"] = 0.00019, ["D"] = 1 },
		["Blue"] = { ["A"] = 0.97, ["B"] = 4000, ["C"] = 0.00096, ["D"] = -1 },
		["Description"] = "Epic"
	},
	[4000] = {
		["Red"] = { ["A"] = 0.0, ["B"] = 3000, ["C"] = 0.00069, ["D"] = 1 },
		["Green"] = { ["A"] = 0.5, ["B"] = 3000, ["C"] = 0.00022, ["D"] = -1 },
		["Blue"] = { ["A"] = 1, ["B"] = 3000, ["C"] = 0.00003, ["D"] = -1 },
		["Description"] = "Superior"
	},
	[3000] = {
		["Red"] = { ["A"] = 0.12, ["B"] = 2000, ["C"] = 0.00012, ["D"] = -1 },
		["Green"] = { ["A"] = 1, ["B"] = 2000, ["C"] = 0.00050, ["D"] = -1 },
		["Blue"] = { ["A"] = 0, ["B"] = 2000, ["C"] = 0.001, ["D"] = 1 },
		["Description"] = "Uncommon"
	},
	[2000] = {
		["Red"] = { ["A"] = 1, ["B"] = 1000, ["C"] = 0.00088, ["D"] = -1 },
		["Green"] = { ["A"] = 1, ["B"] = 000, ["C"] = 0.00000, ["D"] = 0 },
		["Blue"] = { ["A"] = 1, ["B"] = 1000, ["C"] = 0.001, ["D"] = -1 },
		["Description"] = "Common"
	},
	[1000] = {
		["Red"] = { ["A"] = 0.55, ["B"] = 0, ["C"] = 0.00045, ["D"] = 1 },
		["Green"] = { ["A"] = 0.55, ["B"] = 0, ["C"] = 0.00045, ["D"] = 1 },
		["Blue"] = { ["A"] = 0.55, ["B"] = 0, ["C"] = 0.00045, ["D"] = 1 },
		["Description"] = "Trash"
	},
}



GS_CommandList = {
	[1] = "---GearScore Options List---",
   	[2] = "/gs <name> --> Shows you last reported score for player <name>.",
  	--[3] = "/gspam party, raid, or bg -> Reports scores of players in your group.",
	--[4] = "/gspam party <name> -> Whispers scores of players in your party to <name>.",
	[3] = "/gset player -> Toggles display of scores on players.",
	[4] = "/gset item -> Toggles display of scores for items.",
	--[7] = "/gset describe -> Toggles score descriptions for player's scores.",
	[5] = "/gset level -> Toggles iLevel information.",
	[6] = "/gset communicate -> Toggles Communication.",
    --[10] = "/gset average --> Shows Average ItemLevel in Tooltip.",
	[7] = "/gset reset --> Resets GearScore's Options back to Default.",
	--[12] = "/gset compare --> Toggles Display of Comparison info to Tooltip.",
	[8] = "/gset detail --> Toggles Display of Detailed Gear Items in Tooltip.",
	[9] = "/gset ml --> Toggles display of GearScore Masterloot comparison tooltip.",
	[10] = "/gset compare --> Toggles display of comparative info between you and your target's GearScore.",
	--[15] = "/gset prune --> Removes old and low level GearScores from your database.",
	[11] = "/gset purge --> Removes all entries from your database. Use with caution!",
	[12] = "/gset date --> Adds date & Time info to the tooltip",
	[13] = "/gset chat --> Adds GearScore information to Chat Frames.",
	[14] = "/gset transmit <name> --> Transmits your GearScore database to player <name>.",
	[15] = "/gsban <name> --> Toggles rather or not <name> is allowed to send you GearScore Data.",
  	[15] = "/gspam <group> -> Reports scores of players in your group. <group> can be 'party', 'raid', or 'group'",
	[16] = "/gspam <group> <targetchat> -> Whispers scores of players in your <group> to <targetchat> Eample: /gspam party guild",
}

GS_ShowSwitch = {[0] = 2,[1] = 3,[2] = 0,[3] = 1}
GS_ItemSwitch = {[0] = 3,[1] = 2,[2] = 1,[3] = 0}

GS_Zones = {
	["Elwynn Forest"] = "EWF",
	["Eversong Woods"] = "ESW",
	["Dun Morogh"] = "DMG",
	["Tirisfal Glades"] = "TFG",
	["Ghostlands"] = "GSL",
	["Loch Modan"] = "LMD",
	["Silverpine Forest"] = "SPF",
	["Westfall"] = "WSF",
	["Redridge Mountains"] = "RRM",
	["Duskwood"] = "DKW",
	["Hillsbrad Foothills"] = "HBF",
	["Wetlands"] = "WTL",
	["Alterac Mountains"] = "ATM",
	["Arathi Highlands"] = "AHL",
	["Stranglethorn Vale"] = "STV",
	["Badlands"] = "BDL",
	["Swamp of Sorrows"] = "SOS",
	["The Hinterlands"] = "THL",
	["Searing Gorge"] = "SRG",
	["The Blasted Lands"] = "TBL",
	["Burning Steppes"] = "BRS",
	["Western Plaguelands"] = "WPL",
	["Eastern Plaguelands"] = "EPL",
	["The Scarlet Enclave"] = "TSE",
	["Blackrock Mountain"] = "BRM",
	["Deadwind Pass"] = "DWP",
	["Isle of Quel'Danas"] = "IQD",
	["Azuremyst Isle"] = "AZI",
	["Durotar"] = "DRT",
	["Mulgore"] = "MLG",
	["Teldrassil"] = "TLD",
	["Bloodmyst Isle"] = "BMI",
	["Darkshore"] = "DKS",
	["The Barrens"] = "TBR",
	["Stonetalon Mountains"] = "STM",
	["Ashenvale"] = "ASV",
	["Thousand Needles"] = "TSN",
	["Desolace"] = "DSL",
	["Dustwallow Marsh"] = "DWM",
	["Feralas"] = "FRL",
	["Tanaris"] = "TNR",
	["Azshara"] = "AZS",
	["Felwood"] = "FLW",
	["Un'goro Crater"] = "UGC",
	["Winterspring"] = "WTS",
	["Silithus"] = "SLT",
	["Moonglade"] = "MGD",
    ["Hellfire Peninsula"] = "HFP",
    ["Zangarmarsh"] = "ZGM",
    ["Terokkar Forest"] = "TKF",
    ["Nagrand"] = "NGD",
    ["Blade's Edge Mountains"] = "BEM",
    ["Netherstorm"] = "NTS",
    ["Shadowmoon Valley"] = "SMV",
    ["Borean Tundra"] = "BRT",
    ["Howling Fjord"] = "HLF",
    ["Dragonblight"] = "DGB",
    ["Grizzly Hills"] = "GZH",
    ["Zul'Drak"] = "ZLD",
    ["Sholazar Basin"] = "SLB",
    ["Crystalsong Forest"] = "CSF",
    ["Storm Peaks"] = "STP",
    ["Icecrown"] = "ICN",
    ["Wintergrasp"] = "WTG",
    ["Hrothgar's Landing"] = "HTL",
    ["Orgrimmar"] = "ORG",
    ["Dalaran"] = "DAL",
    ["Ulduar"] = "ULD",
	["Auchenai Crypts"] = "ACC",
	["Sethekk Halls"] = "STH",
	["Caverns of Time"] = "COT",
	["Old Hillsbrad Foothills"] = "OHF",
	["City of Ironforge"] = "COI",
	["Unknown Location"] = "XXX",
	["Deadmines"] = "DDM",
	
--	["Shadowfang Keep"] = "SFK",
--	["Stockade"] = "STK",
--	["Gnomeregan"] = "GMR",
--	["Scarlet Monastery"] = "SCM",
--	["Temple of Atal'Hakkar"] = "TAH",
	
	
	["DDM"] = "Deadmines",
	["XXX"] = "Unknown Location",
	["COI"] = "City of Ironforge",
	["OHF"] = "Old Hillsbrad Foothills",
	["COT"] = "Caverns of Time",
	["STH"] = "Sethekk Halls",
	["ACC"] = "Auchenai Crypts",
	["ULD"] = "Ulduar",
	
    ["DAL"] = "Dalaran",
    ["EWF"] = "Elwynn Forest",
	["ESW"] = "Eversong Woods",
	["DMG"] = "Dun Morogh",
	["TFG"] = "Tirisfal Glades",
	["GSL"] = "Ghostlands",
	["LMD"] = "Loch Modan",
	["SPF"] = "Silverpine Forest",
	["WSF"] = "Westfall",
	["RRM"] = "Redridge Mountains",
	["SKW"] = "Duskwood",
	["HBF"] = "Hillsbrad Foothills",
	["WTL"] = "Wetlands",
	["ATM"] = "Alterac Mountains",
	["AHL"] = "Arathi Highlands",
	["STV"] = "Stranglethorn Vale",
	["BDL"] = "Badlands",
	["SOS"] = "Swamp of Sorrows",
	["THL"] = "The Hinterlands",
	["SRG"] = "Searing Gorge",
	["TBL"] = "The Blasted Lands",
	["BRS"] = "Burning Steppes",
	["WPL"] = "Western Plaguelands",
	["EPL"] = "Eastern Plaguelands",
	["TSE"] = "The Scarlet Enclave",
	["BRM"] = "Blackrock Mountain",
	["DWP"] = "Deadwind Pass",
	["IQD"] = "Isle of Quel'Danas",
	["AZI"] = "Azuremyst Isle",
	["DRT"] = "Durotar",
	["MLG"] = "Mulgore",
	["TLD"] = "Teldrassil",
	["BMI"] = "Bloodmyst Isle",
	["DKS"] = "Darkshore",
	["TBR"] = "The Barrens",
	["STM"] = "Stonetalon Mountains",
	["ASV"] = "Ashenvale",
	["TSN"] = "Thousand Needles",
	["DSL"] = "Desolace",
	["DWM"] = "Dustwallow Marsh",
	["FRL"] = "Feralas",
	["TNR"] = "Tanaris",
	["AZS"] = "Azshara",
	["FLW"] = "Felwood",
	["UGC"] = "Un'goro Crater",
	["WTS"] = "Winterspring",
	["SLT"] = "Silithus",
	["MGD"] = "Moonglade",
    ["HFP"] = "Hellfire Peninsula",
    ["ZGM"] = "Zangarmarsh",
    ["TKF"] = "Terokkar Forest",
    ["NGD"] = "Nagrand",
    ["BEM"] = "Blade's Edge Mountains",
    ["NTS"] = "Netherstorm",
    ["SMV"] = "Shadowmoon Valley",
    ["BRT"] = "Borean Tundra",
    ["HLF"] = "Howling Fjord",
    ["DGB"] = "Dragonblight",
    ["GZH"] = "Grizzly Hills",
    ["ZLD"] = "Zul'Drak",
    ["SLB"] = "Sholazar Basin",
    ["CSF"] = "Crystalsong Forest",
    ["STP"] = "Storm Peaks",
    ["ICN"] = "Icecrown",
    ["WTG"] = "Wintergrasp",
    ["HTL"] = "Hrothgar's Landing",
    ["ORG"] = "Orgrimmar"
}



